version: "3.9"

services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
    container_name: rtmp_server
  db:
    build: ./db
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=main_db